#
#
# This is a sample newrelic_plugin.yml file. Please move this file
# to the following location if it is not already there:
#
#     ./config/newrelic_plugin.yml
#
# Where the current directory is the directory where your main program resides and is your current
# directory when you run the main program.
#
# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'YOUR_LICENSE_KEY_HERE'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
  
  # All plugin data goes to collector.newrelic.com
  # host: "collector.newrelic.com"

#
# Agent Configuration:
#
agents:
  varnish:
    # Define one or more agents for each varnish instance
    -
      name: "Varnish 1"
      # -n argument for Varnish
      # vname:
      # host if you want to connect to a remote varnish
      # host: user@hostname
